### ISSUE TITLE
Timeout handling

### ISSUE THREAD

**Issue by Natim** [mozilla-services/syncto#21]
We need to make sure that the sum of all request from the server to other server take less than 30s and add timeouts accordingly.

**Comment by michielbdejong** [comment]
The 503s I saw this morning appeared after less than 5 seconds. Maybe they were real 503s, then? :) I'll update if I see them again.

**Comment by Natim** [comment]
The idea would be to set the time of the request creation and then use this value to calculate the max remaining time before the response has to be send back to the client.

```
request.start_time = time()
requests.request('get', timeout=30+request.start_time-time()-1)
```
