### ISSUE TITLE
Consider adding ``Access-Control-Max-Age`` header to let the browser cache CORS requests.

### ISSUE THREAD

**Issue by Natim** [mozilla-services/syncto#24]
Refs https://github.com/Kinto/kinto/issues/185

**Comment by michielbdejong** [comment]
Ah, that might also help to fix https://github.com/Kinto/kinto.js/issues/170, I guess.

**Comment by Natim** [comment]
Done in Cliquet https://github.com/mozilla-services/cliquet/pull/466
