### ISSUE TITLE
Allow write operations only to certain paths

### ISSUE THREAD

**Issue by michielbdejong** [mozilla-services/syncto#26]
For two scenarios, it would be nice to be able to keep Syncto running for read operations, but refuse to relay write operations altogether:
- if we (initially) launch FxOS Sync only for retrieving data from the cloud, not for uploading it, it would be a nice safety guard to disable writing-to-the-cloud in the Syncto proxy.
- if we discover a problem with devices that are in use, that corrupts people's data in the cloud, we might want to disable writing-to-the-cloud at the Syncto proxy as a damage-limiting measure.

But even in normal operation, writes should only happen to the 'history', 'bookmarks' and 'passwords' collections, never for 'meta' and 'crypto'. There, read-only is enough. How hard would it be to make such a safe-guard build-time configurable?

**Comment by Natim** [comment]
Thank you for filling this issue, this is something we definitely want to implement.

Note that we already have endpoint configuration from the configuration for Kinto so adding this specific would be possible.
