### ISSUE TITLE
Cache Token server credentials for the validity of the BID

### ISSUE THREAD

**Issue by Natim** [mozilla-services/syncto#31]
After thinking this through, it looks like we should cache TokenServer credentials for the validity of the Browser ID assertion only and for a given BID because otherwise we don't validate the BID when using the cache.

**Comment by Natim** [comment]
@rfk I've seen that there are two expiration timestamp in the BID assertion, which one should I be using:

```
{"principal":{"email":"1a84acce1a94409ba5cbea7e2490c41b@api.accounts.firefox.com"},"iat":1443775903393,"exp":1443797513393,"fxa-generation":1443707802938,"fxa-lastAuthAt":1443775912,"fxa-verifiedEmail":"email@mailinator.com","iss":"api.accounts.firefox.com"}
{"exp":2232175968017,"aud":"http://example.com"}
```

**Comment by rfk** [comment]
Whichever is the smaller
