### ISSUE TITLE
Browser cache activated when Total-Records: 0

### ISSUE THREAD

**Issue by michielbdejong** [mozilla-services/syncto#53]
A response to https://syncto.dev.mozaws.net/v1/buckets/syncto/collections/meta/records with Total-Records: 0 gets cached in the browser cache. I think the solution to this would be to add cache control headers like described in https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching_FAQ but I'm not entirely sure how that would affect the normal situation where we want Kinto.js to send conditional requests, and Syncto to respond with 304s.

**Comment by Natim** [comment]
You should receive a 304 if you set the If-Match you can also have a `Total-Records: 0` when in the flushing mode. (See https://github.com/Kinto/kinto.js/issues/44)

**Comment by michielbdejong** [comment]
Yes, we can either fix this in Kinto.js or in Syncto. The fix for Syncto would be https://github.com/michielbdejong/syncto/commit/3c7f8cc65dad62dfe4b0daf2e43a680efa19f4a5 - I confirmed this resolves our current problem, but will test it more to see if it has any undesirable side-effects.

**Comment by michielbdejong** [comment]
I think there is no case where Kinto.js wants to store the same data both in IndexedDB and in the http cache, so if Kinto.js is the only client for Syncto, then a `Cache-Control: no-cache` header would ensure Kinto.js never gets cached http responses from the browser's http cache.

@n1k0 do you agree (after our irc discussion)?

**Comment by n1k0** [comment]
> so if Kinto.js is the only client for Syncto

If this is confirmed and unlikely to change in a near future, yes this sounds good :)
