### ISSUE TITLE
Incorrect response status when sub-request of batch has 412 status

### ISSUE THREAD

**Issue by michielbdejong** [mozilla-services/syncto#78]
A batch request should never return a 412 status code, yet this one does:
<img width="650" alt="screen shot 2016-01-21 at 11 16 29" src="https://cloud.githubusercontent.com/assets/408412/12477708/54b6a418-c031-11e5-8d62-3d38843b8584.png">

The batch consists of one PUT request:
<img width="645" alt="screen shot 2016-01-21 at 11 14 59" src="https://cloud.githubusercontent.com/assets/408412/12477726/77245e1e-c031-11e5-9573-5a83c2278d1e.png">

The 412 response is correct for the subrequest response, but IMO the batch as a whole should still result in a 200.

**Comment by Natim** [comment]
Yes true :+1:

**Comment by Natim** [comment]
So we've written a test to try to reproduce the matter in cliquet. mozilla-services/cliquet#627
The test is passing.

Trying to write the same test in syncto.

**Comment by Natim** [comment]
So we finally understood what the problem was.

We need to find the answer to this question: http://stackoverflow.com/questions/35014250/how-to-have-pyramid-invoke-subrequest-to-go-through-view-config-context-routing
