### ISSUE TITLE
Using X-Client-State header is not RESTful

### ISSUE THREAD

**Issue by michielbdejong** [mozilla-services/syncto#9]
This might not be a problem, but...

Just a note, I realized we are using the same base URL, regardless of which user's data we're looking at. For instance I see kinto.js access http://localhost:8000/v1/buckets/syncto/collections/history/records?_since=1439218393690 in testing to retrieve the 'history' collection of the currently logged in user.

The only situation in which I can imagine this being problematic is if you switch users. Then that URL suddenly represents a different resource than it did when someone else was logged in to the browser. Obviously it's the client's responsibility to remove all locally cached data when a user logs out. But what about the browser's http cache? It might think "Oh, I have that data cached, no need to go to the network to retrieve it." And then suddenly the newly logged in user will see the private data of the recently logged out user.

I'm not sure whether the browser's http cache will consider two requests equal if the X-Client-State header differs. It might be OK. But it does violate the "RESTfulness" best-practice for APIs where each resource has its own URL.

**Comment by n1k0** [comment]
> And then suddenly the newly logged in user will see the private data of the recently logged out user.

And that would be really bad. Is it conceivable the userid becomes part of the urls? That's probably bazookaish, but that would fix the client caching issue.

**Comment by Natim** [comment]
I cannot see a cache system that will not take care of the Authorization header.

**Comment by Natim** [comment]
I am closing for now since we are not doing anything different from what Firefox Sync does on this matter. https://docs.services.mozilla.com/storage/apis-1.5.html#collections (i.e having the client state or client id in the URL)

**Comment by Natim** [comment]
We should probably use the `X-Client-State` as a bucket ID to avoid this.

**Comment by michielbdejong** [comment]
Good idea! The bucket ID is checked to be `'syncto'` in https://github.com/mozilla-services/syncto/blob/master/syncto/views/collection.py#L12 and https://github.com/mozilla-services/syncto/blob/master/syncto/views/record.py#L44. Can we check for `xClientState` there instead?

**Comment by Natim** [comment]
This have been implemented.
